language: java
sudo: false
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petshop;'
cache:
  directories:
    - "$HOME/.m2"
jdk:
  - oraclejdk8
script:
  - set -e
  - mvn clean package

